import { ProjectTypes } from "@/types";

const projects: ProjectTypes[] = [
  {
    name: "Portfolio",
    mainType: "typescript",
    previewLink: "",
    previewImg: "/projects/portfolio.png",
    category: ["Typescript", "NextJs", "ReactJs"],
    description: "",
    githubUrl: "https://github.com/shukabum/Vsportfolioweb",
  },
  {
    name: "Mass-Mailer",
    previewLink: "https://github.com/shukabum/Mass-Mailer",
    mainType: "react",
    previewImg: "/projects/mailer.png",
    category: ["React", "HTML5"],
    description: "",
    githubUrl: "https://github.com/Qudusayo/nft-marketplace",
  },
  {
    name: "Nextech-frontiers",
    previewLink: "https://github.com/shukabum/nextech-website",
    mainType: "react",
    previewImg: "/projects/nextech.png",
    category: ["ReactJs", "Javascript", "Contribution"],
    description: "",
    githubUrl: "https://github.com/nextechfrontiers/nextech-website",
  },
  {
    name: "Portfolio 2",
    mainType: "react",
    previewLink: "https://portfolio-project-f4vt4xeer-shukabum.vercel.app/",
    previewImg: "/projects/portfolio2.png",
    category: ["React", "JavaScript"],
    description: "",
    githubUrl: "https://github.com/shukabum/Portfolio-Project",
  },
  {
    name: "Dalle-Clone",
    previewLink: "https://github.com/shukabum/Dalleclone",
    mainType: "react",
    previewImg: "/projects/Dalle.png",
    category: ["React", "NodeJs", "Javascript"],
    description: "",
    githubUrl: "https://github.com/shukabum/Dalleclone",
  },
  {
    name: "Cypher-School",
    previewLink: "https://cypher-school.netlify.app/",
    mainType: "react",
    previewImg: "/projects/cypher.png",
    category: ["React", "Contribution"],
    description: "",
    githubUrl: "https://github.com/shukabum/Cypher-School",
  },
  {
    name: "Payment-Gateway",
    previewLink: "https://shukabum.github.io/paymentgateway/",
    mainType: "react",
    previewImg: "/projects/payment.png",
    category: ["HTML5", "Contribution"],
    description: "",
    githubUrl: "https://github.com/shukabum/paymentgateway",
  },
  {
    name: "Blender",
    previewLink: "https://github.com/shukabum/Blender",
    mainType: "contribution",
    previewImg: "/projects/portfolio2.png",
    category: ["Blender"],
    description: "",
    githubUrl: "https://github.com/shukabum/Blender",
  },

  {
    name: "Movies-Search",
    previewLink: "https://shukabum.github.io/Movies-Search",
    mainType: "contribution",
    previewImg: "/projects/movies.png",
    category: ["HTML5", "API"],
    description: "",
    githubUrl: "https://github.com/shukabum/Movies-Search",
  },
  {
    name: "Travel-Planner-pro",
    previewLink: "https://github.com/shukabum/travel-planner-pro",
    mainType: "react",
    previewImg: "/projects/travel.png",
    category: ["HTML5", "API", "React", "Contribution"],
    description: "",
    githubUrl: "https://github.com/me-loser/travel-planner-pro",
  },
  {
    name: "Reslink_Dashboard",
    previewLink: "",
    mainType: "react",
    previewImg: "/projects/eslink.png",
    category: ["HTML5", "API", "React", "Contribution"],
    description: "",
    githubUrl: "https://github.com/shukabum/Reslinkdash",
  },
  {
    name: "AgentX-Travel-agent AI",
    previewLink: "https://fetch.ai/integrations",
    mainType: "react",
    previewImg: "/projects/ajentx.png",
    category: ["HTML5", "API", "React", "Contribution", "AI", "Python"],
    description: "",
    githubUrl: "https://github.com/shukabum/uAgents",
  },
  {
    name: "Medicare",
    previewLink: "https://medicare-vert.vercel.app/",
    mainType: "react",
    previewImg: "/projects/Medicare.png",
    category: ["HTML5", "API", "React", "Contribution", "AI", "Python"],
    description: "",
    githubUrl: "https://github.com/shukabum/Tinkerquest-medicare",
  },
  {
    name: "StudentPedia",
    previewLink: "",
    mainType: "react",
    previewImg: "/projects/studentpedia.png",
    category: ["HTML5", "API", "React", "Contribution", "AI", "Python"],
    description: "",
    githubUrl: "https://github.com/shukabum/student-data",
  },
  {
    name: "Chrome-Extensions",
    previewLink: "",
    mainType: "react",
    previewImg: "/projects/ajentx.png",
    category: ["HTML5", "API", "React", "Contribution", "AI", "Python"],
    description: "",
    githubUrl: "https://github.com/shukabum/firstextension",
  },
  {
    name: "Site-store",
    previewLink: "",
    mainType: "react",
    previewImg: "/projects/Github.png",
    category: ["HTML5", "API", "React", "Contribution", "AI", "Python"],
    description: "",
    githubUrl: "https://github.com/shukabum/site-store",
  },
];

export default projects;
